apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-instance-pv2
  labels:
    pv-usage: mysql-instance
spec:
  claimRef:
    name: mysql-instance-pv
    namespace: default
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/mysql-instance-pv-2/