apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "mysql-instance-pv"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 1Gi
  volumeName: "mysql-instance-pv"
  selector:
    matchLabels:
      pv-usage: mysql-instance